/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@publiclogic/golden-path"],
  async rewrites() {
    return [
      // The Paper Trail's PDF export lives at the spec's locked URL
      // (/paper-trail/{year}/{slug}.pdf, §1/§7) but is generated by a
      // post-build CI job into public/paper-trail/pdf/ rather than sitting
      // in the dynamic [year]/[slug] route tree.
      {
        source: "/paper-trail/:year/:slug.pdf",
        destination: "/paper-trail/pdf/:year/:slug.pdf",
      },
    ];
  },
};

export default nextConfig;
