import fs from "node:fs";
import path from "node:path";
import type { PaperTrailItem } from "./schema";

/**
 * PDFs are generated by a post-build CI job (§7), not the Next build, so a
 * freshly merged item can briefly have no PDF yet. Checking for the file
 * lets the share row say "PDF generating" instead of linking to a 404.
 */
export function pdfFileExists(item: Pick<PaperTrailItem, "year" | "slug">): boolean {
  const file = path.join(process.cwd(), "public", "paper-trail", "pdf", item.year, `${item.slug}.pdf`);
  return fs.existsSync(file);
}
